### ISSUE TITLE
Access to a pretrained model

### ISSUE THREAD

**Issue by PierreColombo** [WebNLG/challenge-2020#3]
Dear Organizers,
Thanks a lot for outsourcing the results of the challenges. 

We would like to work on the outputs of the competitions. To test our ideas would need to have access to a pretrained model that solve the task. We have seen the list of the papers here https://github.com/WebNLG/challenge-2020/tree/main/submissions but could not find any pretrained models. 
Do you have access to a pretrained model that we could use to do the inference ?

Kindest regards,
Pierre

**Comment by Shimorina** [comment]
Hello,

I would contact the participants of the challenge and ask them if they saved their checkpoints. We didn't collect any pretrained models.

**Comment by PierreColombo** [comment]
Ok many thanks for the fast reply.
